### PR TITLE
Define `__RGBDS_VERSION__` as the output of `rgbasm --version` (sans "rgbasm")

### LINKED ISSUE #824: [Feature request] `__RGBDS_VERSION__ EQUS` for the version string
The existing `EQU` constants are convenient for checking version requirements, but when reporting them to the user, it involves some lengthy format logic:

```
; prints "This is rgbds v0.5.0-rc2!"
print "This is rgbds v{d:__RGBDS_MAJOR__}.{d:__RGBDS_MINOR__}.{d:__RGBDS_PATCH__}"
if DEF(__RGBDS_RC__)
print "-rc{d:__RGBDS_RC__}"
endc
println "!"
```

Even ignoring the possibility of `__RGBDS_RC__`, it has to `d`-format three variables. This would be shorter:

```
println "This is rgbds {__RGBDS_VERSION__}!"
```

It would serve a similar purpose as `__ISO_8601_UTC__`, even though the components are also defined as `__UTC_YEAR__`, `__UTC_MONTH__`, etc.

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #824

### CODE REVIEW

**Comment by Rangi42** [comment]
I'd like to see this added in 0.5.0 if at all, since the earlier it's available, the less people will have to check `if DEF(__RGBDS_VERSION__)`.

**Comment by ISSOtm** [comment]
This gives `__RGBDS_VERSION__` different semantics from concatenating the three `__RGBDS_*__` symbols (`rgbasm v0.5.0-rc2-42-g0123456-dirty`)

**Comment by Rangi42** [comment]
For users of a release version that won't matter (right? `get_package_version_string` is used for both `--version` printout and `__RGBDS_VERSION__`), and for those using `master` I think that's an advantage, since printing `__RGBDS_VERSION__` will be commit-accurate.

**Comment by ISSOtm** [comment]
Well, that can currently be obtained with `rgbasm -D__RGBDS_VERSION__="$(rgbasm --version | cut -d ' ' -f 2-)"`, fwiw.

**Comment by ISSOtm** [comment]
Besides, a `v` is prepended to the version, too, as part of the tag name.

**Comment by Rangi42** [comment]
> Besides, a `v` is prepended to the version, too, as part of the tag name.

Yes? That's the point, to have `__RGBDS_VERSION__` match what's printed by `--version`, so a project doesn't have to format the components itself.

Compare:

```
if __RGBDS_MAJOR__ < 1
    print "We require rgbasm v1.0.0 or later. You have rgbasm v{d:__RGBDS_MAJOR__}.{d:__RGBDS_MINOR__}.{d:__RGBDS_PATCH__}"
    if DEF(__RGBDS_RC__)
        print "-rc{d:__RGBDS_RC__}"
    endc
    println " or a Git commit between that and the next release. (Check 'rgbasm --version'.)"
endc
```

vs

```
if __RGBDS_MAJOR__ < 1
    print "We require rgbasm v1.0.0 or later. You have rgbasm {__RGBDS_VERSION__}."
endc
```

**Comment by Rangi42** [comment]
Compare with how `gcc` defines `__GNUC__`/`__GNUC_MINOR__`/`__GNUC_PATCHLEVEL__` components, but also a `__VERSION__` string. Or FLTK defines `FL_MAJOR_VERSION`/`FL_MINOR_VERSION`/`FL_PATCH_VERSION` but also `FL_VERSION`. I think this is a common pattern.

**Comment by ISSOtm** [comment]
I guess, then.

**Pull request merged**
