### PR TITLE
Refactor the lexer's `lookupExpansion` macro to not need `LOOKUP_PRE/POST_NEST`

### PR DESCRIPTION
**Pull request by Rangi42**
This macro was only used twice, in `beginExpansion` and `lexer_DumpStringExpansions`, with `getExpansionAtDistance` already containing an inlined and slightly modified version of `lookupExpansion` (retaining the `LOOKUP_PRE_NEST` and `LOOKUP_POST_NEST` macros, but with both of them doing nothing).

Not using an X macro here makes the actual control flow in both places more obvious, and I think the repeated code is acceptable for the same reasons as the similar-but-distinct implementations of `readString`, `appendStringLiteral`, `yylex_NORMAL`, and `yylex_RAW`.

### CODE REVIEW

**Comment by Rangi42** [comment]
I think `getExpansionAtDistance`'s implementation was already inlined because it subtracts `exp->totalLen - exp->skip` from the distance instead of `lookupExpansion`'s `exp->totalLen + exp->skip`, but don't know why it does that.

**Comment by Rangi42** [comment]
If you *do* want to factor out the common `for` loop in those three cases (assuming the `getExpansionAtDistance` really should look like the other two), then this would work:

```c
#define lookupExpansion(dist, ...) do { \
	for (struct Expansion *exp = lexerState->expansions; exp; exp = exp->firstChild) { \
		/* Find the closest expansion whose end is after the target */ \
		while (exp && exp->totalLen + exp->distance <= (dist)) { \
			(dist) -= exp->totalLen + exp->skip; \
			exp = exp->next; \
		} \
		/* If there is none, or it begins after the target, stop at the previous level */ \
		if (!exp || exp->distance > (dist)) \
			break; \
		/* We know we are inside of that expansion */ \
		(dist) -= exp->distance; /* Distances are relative to their parent */ \
		/* Otherwise, register this expansion and repeat the process */ \
		__VA_ARGS__ \
	} \
} while (0)


static struct Expansion *getExpansionAtDistance(size_t *distance)
{
	struct Expansion *expansion = NULL; /* Top level has no "previous" level */

	lookupExpansion(*distance, {
		expansion = exp;
	});

	return expansion;
}


static void beginExpansion(size_t distance, uint8_t skip, char const *str, bool owned,
			   char const *name)
{
	size_t size = strlen(str);

	/* Do not expand empty strings */
	if (!size)
		return;

	distance += lexerState->expansionOfs; /* Distance argument is relative to read offset! */

	/* Increase the total length of all parents, and return the topmost one */
	struct Expansion *parent = NULL;
	unsigned int depth = 0;

	lookupExpansion(distance, {
		exp->totalLen += size - skip;
		parent = exp;

		if (name && depth++ >= nMaxRecursionDepth)
			fatalerror("Recursion limit (%zu) exceeded\n", nMaxRecursionDepth);
	});

	struct Expansion **insertPoint = parent ? &parent->firstChild : &lexerState->expansions;

	[...]
}


void lexer_DumpStringExpansions(void)
{
	if (!lexerState)
		return;
	struct Expansion **stack = malloc(sizeof(*stack) * (nMaxRecursionDepth + 1));
	unsigned int depth = 0;
	size_t distance = lexerState->expansionOfs;

	if (!stack)
		fatalerror("Failed to alloc string expansion stack: %s\n", strerror(errno));

	lookupExpansion(distance, {
		/* Only register EQUS expansions, not string args */
		if (exp->name)
			stack[depth++] = exp;
	});

	while (depth--)
		fprintf(stderr, "while expanding symbol \"%s\"\n", stack[depth]->name);
	free(stack);
}
```

**Comment by ISSOtm** [comment]
Yeah, `getExpansionAtDistance` was, I think, not factored out by mistake when I decided that the copy-paste was too non-trivial.

I really like the version with the code block, too, but does it work? I thought it wouldn't.

**Comment by Rangi42** [comment]
It does work. I didn't invent the `__VA_ARGS__` for `{ ... }` trick, other projects have used it.

**Review by ISSOtm — APPROVED** [review]

**Pull request merged**
