### PR TITLE
Improve link map formatting

### PR DESCRIPTION
**Pull request by rlewicki**
This task ticks off one of the tasks mentioned in #1099. I'll have a look at the other two tomorrow.

### CODE REVIEW

**Review by ISSOtm — APPROVED** [review]

**Review by avivace — APPROVED** [review]

**Comment by ISSOtm** [comment]
CI fails because it's caching the entire `test` directory identically regardless of OS, it seems.

**Comment by rlewicki** [comment]
Does this mean that we should store different key per platform? So instead:
```
key: ${{ hashFiles('test/fetch-test-deps.sh') }}
```
we would do
```
key: ${{ hashFiles('test/fetch-test-deps.sh') }}-${{ matrix.os }}
```
?
What do you think of that solution?

**Comment by ISSOtm** [comment]
I'd rather flip the two (human-readable part first), and you will probably need to get the architecture in there too for the Windows tests.

We should've caught that earlier, ah well. :T

**Comment by ISSOtm** [comment]
Sorry it took a while to merge this, I had forgotten about it... ^^'

**Comment by rlewicki** [comment]
No worries!

**Pull request merged**
