### PR TITLE
Fix the rgbgfx color curve

### LINKED ISSUE #1199: `rgbgfx --color-curve` gives dark-looking results
I think this is because the `reverse_curve` array maps 8-bit original values to 5-bit curved values; but then with the R,G,B values get combined into one 16-bit value, it does 8-to-5-bit shifting, and then 5 bits get shifted down to 2.

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #1199

### CODE REVIEW

**Review by ISSOtm — COMMENTED** [review]
Was this tested on something?

**Comment by Rangi42** [comment]
Not beyond checking that it builds and runs with `--color-curve` specified, and the .pal output has changed. Extending the gfx test infrastructure to allow palette testing just for this seemed excessive.

**Comment by ISSOtm** [comment]
Testing by @coffeevalenbat shows that the output image has *reasonable* output scale. So the bug that this PR purports to fix is indeed fixed.

The curve correction itself may be broken, but we can take care of that separately.

**Review by ISSOtm — APPROVED** [review]
Testing by @coffeevalenbat shows that the output image has *reasonable* output scale. So the bug that this PR purports to fix is indeed fixed.

The curve correction itself may be broken, but we can take care of that separately.

**Pull request merged**
