### PR TITLE
Refer to "end of line", not "newline"

### LINKED ISSUE #1514: Rename "newline" to "end of line"
This may make some error messages more clear/accurate, and would match "end of file" and "end of buffer".

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #1514

### CODE REVIEW

**Review by ISSOtm — COMMENTED** [review]
Oh, yeah, that makes sense. Though, in that vein, consider if we should call “end of buffer” some “end of file” or “end of input” instead.

**Comment by Rangi42** [comment]
Calling it "end of file" would sometimes result in error messages saying "expected end of file or end of file". Calling it "end of input" sounds to me like the end of *all* the input, not just some inner buffer. Though I agree "buffer" is a technical term, would be nice to have a better one. (What exactly are they for? The end of `INCLUDE`d files? Expanded `EQUS` and/or {interpolations}` and/or macro args?)

**Comment by ISSOtm** [comment]
It's for the end of included files.

**Comment by Rangi42** [comment]
> It's for the end of included files.

Apparently it's also for REPT/FOR and MACRO bodies.

**Comment by Rangi42** [comment]
Let's leave potentially renaming EOB for another PR?

**Pull request merged**
