### PR TITLE
Don't delete script.cpp after building

### PR DESCRIPTION
**Pull request by Rangi42**
asm/main.cpp and asm/lexer.cpp both include asm/parser.hpp, so the Makefile declares them that way, which is why asm/parser.hpp is considered a secondary file and is preserved when `make` finishes.

link/main.cpp incudes link/script.hpp, but the Makefile did not declare it that way, so link/script.cpp was being deleted after `make` finished.

### CODE REVIEW

**Comment by ISSOtm** [comment]
What's being lost by having that file auto-removed after building?

**Comment by Rangi42** [comment]
Being able to easily read it (I've sometimes consulted it), and symmetry with the asm parser.

**Comment by ISSOtm** [comment]
It is possible to read it after building by requesting Make to build it explicitly (`make src/link/script.cpp`).

The symmetry is not necessary, because the reason for that rule is to let Make know that the header file required by the lexer can be obtained by processing the parser. Since the linker script parser file also contains its own lexer, the header file is only used by itself.

**Comment by Rangi42** [comment]
The thing is, I think we *should* have `src/link/main.o: src/link/script.hpp` in the Makefile, because main.o does depend on script.hpp. And once we add that line, `make` fails unless we also add the `src/link/script.hpp: src/link/script.cpp` line.

**Comment by ISSOtm** [comment]
> The thing is, I think we _should_ have `src/link/main.o: src/link/script.hpp` in the Makefile, because main.o does depend on script.hpp (main.cpp includes it). And once we add that line, `make` fails unless we also add the `src/link/script.hpp: src/link/script.cpp` line.

Look closer, there's a subtle troll in there: `#include "link/script.hpp"` references <code><i>include</i>/link/script.hpp</code>—you'd need `#include "script.hpp"` to get the file in `src`. (Confusing? Certainly.)

Note that as I looked into this, I realised that `script.y` does *not* `#include "link/script.hpp"`, so we wouldn't get a warning from a declaration/definition mismatch. Oops?

> (Or if it's not necessary, why do we need `src/asm/main.o: src/asm/parser.hpp`?)

That specific line is there to sequence the assembling of `main.o` after the processing of `parser.y`, as the `.hpp` file is a product of the latter.

**Pull request merged**
