### PR TITLE
Summarize used and free space at the end of the .map file

### LINKED ISSUE #1046: Summarize free space at the end of the .map file
Currently the .map file ends with a summary of used space by section type:

```
USED:
    ROM0: $3fa0 bytes in 1 bank
    ROMX: $1db849 bytes in 119 banks
    SRAM: $78d8 bytes in 4 banks
    WRAM0: $0fda bytes in 1 bank
    WRAMX: $5b6b bytes in 7 banks
    HRAM: $0070 bytes in 1 bank
```

It could be useful to summarize free space as well, at least in the used banks, since it's nontrivial to calculate by checking the size of each type of bank.

For example:

```
USED:
    ROM0: $3fa0 bytes in 1 bank ($0060 free)
    ROMX: $1db849 bytes in 119 banks ($07b7 free)
    SRAM: $78d8 bytes in 4 banks ($0728 free)
    WRAM0: $0fda bytes in 1 bank ($0026 free)
    WRAMX: $5b6b bytes in 7 banks ($1495 free)
    HRAM: $0070 bytes in 1 bank ($000f free)
```

(This cannot take unused banks into account because rgblink doesn't know what MBC the ROM will ultimately use or how many total banks there will be.)

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #1046

Example output:

```
SUMMARY:
  ROM0: 16288 bytes used / 96 free
  ROMX: 1947894 bytes used / 1802 free in 119 banks
  SRAM: 30936 bytes used / 1832 free in 4 banks
  WRAM0: 4058 bytes used / 38 free
  WRAMX: 23403 bytes used / 5269 free in 7 banks
  HRAM: 127 bytes used / 0 free
```

### CODE REVIEW

**Comment by ISSOtm** [comment]
Should the free amount be printed in decimal? I'd expect it not to matter unless it's small, and then a decimal amount should be easier for a human to apprehend than a hex one.

**Comment by Rangi42** [comment]
SLACK and EMPTY amounts are also printed in hex, and I think it would be also potentially confusing to compare a hex used with a decimal free value.

**Comment by ISSOtm** [comment]
Strictly speaking, the three values are redundant (the free amount is just a subtraction), so at least printing them in decimal would at least spare the conversion, is what I'm thinking.
Maybe those amounts should also be printed in decimal, as well.

**Comment by Rangi42** [comment]
For the EMPTY and SLACK values, those are interspersed with sections' and labels' addresses; I like that them all being in hex makes them more obviously comparable. For example, `SECTION: $0100-$014f ($0050 bytes) ["Header"]` is more obvious to me than `SECTION: $0100-$014f (80 bytes) ["Header"]`; or seeing one section end at `$a5e8` and the next start at `$a600`, it makes sense to have `EMPTY: $0017 bytes` between.

On the other hand, the SUMMARY is independent of all that. If you prefer decimal, I think that looks fine here too:

```
SUMMARY:
  ROM0: 16288 bytes used / 96 free
  ROMX: 1947894 bytes used / 1802 free in 119 banks
  SRAM: 30936 bytes used / 1832 free in 4 banks
  WRAM0: 4058 bytes used / 38 free
  WRAMX: 23403 bytes used / 5269 free in 7 banks
  HRAM: 127 bytes used / 0 free
```

**Comment by ISSOtm** [comment]
Yeah, that seems reasonable.

**Pull request merged**
