### PR TITLE
Use `setmode` instead of `fdopen`

### PR DESCRIPTION
**Pull request by Rangi42**
Based on https://github.com/gbdev/rgbds/pull/1502#issuecomment-2358489367

I'll see if this fixes the build in OpenBSD.

### CODE REVIEW

**Comment by Rangi42** [comment]
It did not:

image

**Comment by ISSOtm** [comment]
And if you remove the “POSIX SOURCE” flag from the makefile?

**Comment by Rangi42** [comment]
No, just removing `-D_POSIX_C_SOURCE=200809L` breaks the build in Cygwin (tested on Windows 7).

**Comment by ISSOtm** [comment]
Yes, but what about the combination thereof?

**Comment by Rangi42** [comment]
I don't know, I can't get Cygwin to work any more.

I'm just going to merge this, since it replaces a POSIX call with a standard C call to achieve the same result.

**Pull request merged**
