### PR TITLE
Use `std::string` for most intermediate parsed strings

### PR DESCRIPTION
**Pull request by Rangi42**
To do:

- [x] Use `std::string` for most intermediate parsed strings. *[This works, but is slow!]*
- [x] Pass `std::string` references instead of `.c_str()` pointers to the parser's semantic functions. *[This works, but is still slow!]*
- [x] Use `std::string` for quoted string literals in the lexer, and remove out `String` struct. ***[This is not fully done!]***
- [ ] Symbol values, macro arguments, and so forth are still pointers to C-style strings with unclear ownership semantics (i.e. we still have "leaks as a feature").

Possible optimization opportunities:

- Complete get rid of the `String` struct, since it's 256 bytes large, and use `std::string` instead.
- Use `std::move` on large parser values whenever possible; avoid copying strings in general.
- Reserve space in strings before building them up.
- Pass `std::string_view`, not `const std::string &` (and create these from C string literals or `char const *` pointers-to-buffers)

### CODE REVIEW

**Comment by ISSOtm** [comment]
The `String` structure has been deleted, and thus the parser no longer copies that large buffer around.

That said, it doesn't compile yet, because:
- [ ] I haven't finished porting `strfmt` yet,
- [ ] the two members of `fmt` need to be rewritten to append to a `std::string` instead,
- [ ] and the lexer needs to be adapted to use a `std::string` when expanding interpolations.

**Comment by Rangi42** [comment]
@ISSOtm Thank you! Although your commit mixed the in-progress lexer changes with the works-as-is changes in the parser to refactor its semantic functions. I've split those up; currently the first two commits each build+test correctly, and the third is your WIP.

**Comment by Rangi42** [comment]
These functions in the parser are still given `.c_str()` pointers. If any of them are only ever called with `std::string`s, never with raw points to `'\0'`-terminated buffers, then they could be adapted to take `std::string const &` instead. (Or, once the lexer is using `std::shared_ptr<std::string>` instead of its mess of owned/unowned buffer pointers, then even more of these could be adapted.)

- [ ] `charmap_Add`
- [ ] `charmap_Convert`
- [ ] `charmap_HasChar`
- [ ] `charmap_New`
- [ ] `charmap_Set`
- [ ] `failAssertMsg`
- [ ] `fstk_RunFor`
- [ ] `fstk_RunInclude`
- [ ] `fstk_RunMacro`
- [ ] `out_CreateAssert`
- [ ] `rpn_BankSection`
- [ ] `rpn_BankSymbol`
- [ ] `rpn_SizeOfSection`
- [ ] `rpn_StartOfSection`
- [ ] `rpn_Symbol`
- [ ] `sect_BinaryFile`
- [ ] `sect_BinaryFileSlice`
- [ ] `sect_NewSection`
- [ ] `sect_SetLoadSection`
- [ ] `sym_AddEqu`
- [ ] `sym_AddLabel`
- [ ] `sym_AddLocalLabel`
- [ ] `sym_AddMacro`
- [ ] `sym_AddString`
- [ ] `sym_AddVar`
- [ ] `sym_Export`
- [ ] `sym_FindExactSymbol`
- [ ] `sym_FindScopedValidSymbol`
- [ ] `sym_RedefEqu`
- [ ] `sym_RedefString`

**Comment by Rangi42** [comment]
Okay, something about this new approach has [improved performance](https://pastebin.com/yc6jKWKe), so I'm going to merge it as-is, and the lexer buffer refactoring (to maybe use `std::shared_ptr<std::string>` can be its own PR.

**Pull request merged**
