### PR TITLE
Use `std::vector` for rgbfix ROMX data

### PR DESCRIPTION
**Pull request by Rangi42**
This would have been part of #1313, but this particular commit is failing CI on 32-bit MinGW.

### CODE REVIEW

**Comment by Rangi42** [comment]
I don't know why specifically 32-bit MinGW is failing here. :/

**Review by ISSOtm — DISMISSED** [review]
Been a while since RGBFIX got any changes... ^^

**Comment by Rangi42** [comment]
@ISSOtm This is not ready to be approved -- it breaks the 32-bit MinGW CI.

**Comment by ISSOtm** [comment]
> I don't know why specifically 32-bit MinGW is failing here. :/

I guess we need to debug the executables... I'm not used to Windows debugging, myself ☹️

**Comment by ISSOtm** [comment]
> I don't know why specifically 32-bit MinGW is failing here. :/

Hunch: Windows is bad at reporting missing DLLs on the CLI. Does switching to C++ require new libs?

**Comment by CasualPokePlayer** [comment]
> > I don't know why specifically 32-bit MinGW is failing here. :/
> 
> Hunch: Windows is bad at reporting missing DLLs on the CLI. Does switching to C++ require new libs?

C++ programs until MinGW would end up requiring libstdc++ (and there's also other dlls that seems to be linked to). `rgbds-canary-mingw-win32` itself would provide all the required dlls for running its programs, but `testing-programs-mingw-win32` does not. This also holds true for the 64 bit variants, however, since the host machine is a 64 bit with 64 bit msys2/mingw probably installed, it likely already has the needed dlls somewhere in the path, while the same is not true for the 32 bit version.

**Comment by Rangi42** [comment]
I think you're right about this being a DLL issue! It just needed `-static-libstdc++` to go with `-static-libgcc`.

**Comment by Rangi42** [comment]
Combined with #1313.

**Pull request closed without merging**
