### PR TITLE
Allow `expr * 0` and `expr & 0` to be asm-time constant 0

### LINKED ISSUE #977: Operations that always have the same value can be assembly-time constant
- `Foo * 0` is always `0`
- `Foo & 0` is always `0`
- `Foo - Foo` is always `0`
- `Foo ^ Foo` is always `0`

These could be constant even when `Foo` is floating and unaligned.

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #977

### CODE REVIEW

**Comment by Rangi42** [comment]
`checkpatch` complains "do not use assignment in if condition", but let's disregard it like in https://github.com/gbdev/rgbds/pull/976#discussion_r800090641.

**Comment by ISSOtm** [comment]
I don't think this is worth the complexity, as I stated in https://github.com/gbdev/rgbds/issues/977#issuecomment-1030686698.

**Comment by Rangi42** [comment]
I thought you were referring to the more complex suggestions in that issue; `tryConstZero` turned out shorter than I expected.

**Comment by Rangi42** [comment]
Are we already able to do things like `db Foo * CC + Bar * !CC`? If so this can just be closed.

**Comment by ISSOtm** [comment]
Works for `db` always, not in "constant contexts".

**Comment by Rangi42** [comment]
Hm, okay. That's probably sufficient.

**Pull request closed without merging**
