### PR TITLE
Allow underscores in graphics constants

### PR DESCRIPTION
**Pull request by martendo**
Underscores in graphics constants were not part of #622.

Unlike other numeric literals, an underscore immediately following the backtick is now valid, like `` `_1 ``. I'm unsure whether or not this behaviour is wanted, and it's inconsistent with the other numeric formats, but it can easily be changed.

### CODE REVIEW

**Comment by Rangi42** [comment]
I can't reproduce this: `_` in graphics constants still looks entirely invalid.
``println `_33221100`` gives ``Invalid graphics constant, no digits after '`'``.
`opt gPQRS` and then ``println `SSRRQQPP`` does the same.
Leaving out the `_` from either prints `$F0CC` as expected.
`opt gAB_C` and then ``println `CC__BBAA`` also prints `$F0CC`, demonstrating why they don't allow `_`s.

**Comment by martendo** [comment]
Oh, I completely overlooked that! Sorry about this then.

**Comment by Rangi42** [comment]
No problem. I am copying the `for (;; shiftChar())` refactor from here for consistency. :)

**Comment by martendo** [comment]
I didn't realize earlier, but it might be worth noting that binary literals have the same issue: `opt b_X` then `%X_X_X_X_` yields $AA, for example.

**Pull request closed without merging**
