### PR TITLE
Remove empty .out and .err test files

### PR DESCRIPTION
**Pull request by Rangi42**
In #1229 I suggested organizing the tests into subdirectories. But actually I can't think of any besides "has error output" and "doesn't print any errors"; plus that would affect the filenames in all the output and require a lot of editing.

This is a simpler way to make the test directory contents smaller: don't store empty files, just use `/dev/null` for those. If an empty .out or .err file *is* present it'll work fine, but it's not required.

I only did this for rgbasm because it's the only program with a substantial amount of empty test output files.

### CODE REVIEW

**Comment by ISSOtm** [comment]
Yeahhhh... pretty sure Windows is going to balk at `/dev/null`.

**Comment by Rangi42** [comment]
The whole test framework requires bash anyway; doesn't MinGW provide a `/dev/null` too?

**Comment by ISSOtm** [comment]
I know Bash has special handling for *redirections*, but not to/from `/dev/null`. I'd also be surprised if MinGW was able to provide that file: why would the MSVC-compiled RGBDS perform any special handling for that path, and how would MinGW intercept path resolution?

**Comment by Rangi42** [comment]
Well, it passes CI. :woman_shrugging:

**Comment by vulcandth** [comment]
> Well, it passes CI. 🤷‍♀️

Seems legit.

**Comment by pinobatch** [comment]
I don't think MinGW does this, but I know the C library of DJGPP (GCC targeting MS-DOS + DPMI) treats the name `/dev/` at the root of each drive specially, [emulating some of the device files](https://www.delorie.com/djgpp/v2faq/faq22_21.html) that a \*n?x system puts there.

**Comment by Rangi42** [comment]
(`/dev/null` is common/fundamental enough that I would not expect a GNU software environment like MinGW to not provide it; plenty of the build scripts involved must use it.

**Comment by ISSOtm** [comment]
> Well, it passes CI. 🤷‍♀️ Maybe it uses Windows' `NUL` device.

Yeah, but I'm not confident that CI itself isn't failing to catch some breakage. We've had that happen before.

**Comment by Rangi42** [comment]
Also test.ash already redirects some output to /dev/null.

**Comment by Rangi42** [comment]
> > Well, it passes CI. 🤷‍♀️ Maybe it uses Windows' `NUL` device.
> 
> Yeah, but I'm not confident that CI itself isn't failing to catch some breakage. We've had that happen before.

It's running the tests successfully in Windows though...

**Comment by ISSOtm** [comment]
Bash has an annoying tendency to swallow errors, though. I'd like to investigate before OK'ing this.

**Comment by Rangi42** [comment]
> why would the MSVC-compiled RGBDS perform any special handling for that path, and how would MinGW intercept path resolution?

So, the rgbds executables don't have to provide any special /dev/null handling. I only updated the test.sh script, which runs in bash; and bash on Windows still supports /dev/null for anything (imagine the issues if it didn't).

**Comment by Rangi42** [comment]
> Bash has an annoying tendency to swallow errors, though. I'd like to investigate before OK'ing this.

Anything in particular we should be investigating? Test system configs that GitHub Actions doesn't provide?

We can't/don't need to test POSIX `sh` because test.sh has `#!/usr/bin/env bash`; I don't thing we need `set -e` because the tests need to be allowed to fail; bash won't be swallowing their output because it gets correctly saved as `> $output 2> $errput`... I'm really not sure what failures CI might be hiding here.

**Comment by Rangi42** [comment]
Okay, so: the [RGBDS install instructions](https://rgbds.gbdev.io/install#windows) allow three ways to support Windows.

1. WSL / Linux-like environments: These will of course support `/dev/null`.
2. Cygwin / MSYS2: These also support `/dev/null`. They do automatic path mangling, e.g. converting between `C:/foo` and `/cygdrive/c/foo`. This includes `nul` and `/dev/null`. MSYS2 has some [patches](https://github.com/msys2/MSYS2-packages/tree/master/msys2-runtime), e.g. a `MSYS2_ARG_CONV_EXCL` environment variable to disable this for some paths, but it definitely lets `bash` support running scripts that use `/dev/null`.
3. None of those: Not sure what this would encompass. For just *using* RGBDS you can download the .exes. For [*contributing*](https://github.com/gbdev/rgbds/blob/master/CONTRIBUTING.rst) to it, to run the tests you at least need an environment with a POSIX shell and `bash`, and that basically means options 1 or 2.

Anything else we should check regarding this?

**Comment by Rangi42** [comment]
From the above investigating I'm pretty certain that on any platform where we can currently run test.sh, redirecting to `/dev/null` will work. But if it doesn't, we can do this:

```bash
if [ -e /dev/null ]; then
    EMPTY=/dev/null
else
    EMPTY=NUL # Windows
fi
```

**Comment by Rangi42** [comment]
@ISSOtm I've added a check for `/dev/null` or `NUL` just in case (including in the RGBLINK test script), although I still don't expect any supported platforms to have this issue (since the methods for getting a POSIX environment on Windows will all AFAIK end up also rewriting special paths).

**Comment by Rangi42** [comment]
(Don't squash this when/if merging.)

**Comment by ISSOtm** [comment]
Okay, so my theory as to why this change works even on Windows, is that we're only ever passing `/dev/null` to MinGW executables (the shell itself, and `sed`), and I think those have special handling in the MinGW libc.

Anyhow, [since the affected tests can still fail](https://github.com/ISSOtm/rgbds/actions/runs/6984571450/job/19007585905), I'm confident enough in the patch; so let's keep it simple and not add the `NUL` thing.

**Review by ISSOtm — APPROVED** [review]

**Comment by ISSOtm** [comment]
(I'll let @Rangi42 re-review if she desires, and push the merge button.)

**Pull request merged**
