### PR TITLE
Deprecate `LDIO`

### PR DESCRIPTION
**Pull request by Rangi42**
I already expect the results of [our polls](https://discord.com/channels/303217943234215948/790920525253836912/1313684830814343230) will be to deprecate `ldio [...]` but not `ld [$ff00+...]`, so went ahead and implemented it in what should be an efficient way.

(In the test case, I know `ld [$ff11], a` and `ld a, [$ff11]` assemble to different opcodes than the rest; they're just there for completeness, and they illustrate https://github.com/gbdev/rgbds/pull/1567/commits/b0495b3d5b919cfae74ef2ebd78eafdf148f7690.)

### CODE REVIEW

**Comment by Rangi42** [comment]
Frankly it might be simpler to just remove, since that would let people do a one-line `DEF ldio EQUS "ldh"` "fix".

**Comment by vulcandth** [comment]
Unpopular opinion... Too much deprecation. I say just remove it, and let the assembler errors notify people they need to update their code. It's a simple replace anyways.. I know lots of people who ignore those deprecation warnings until a release causes it to stop building... And then they might just stay on the old version anyways.

*Prepares for incoming rant* :P

**Comment by Rangi42** [comment]
Just to note, re: allowing multiple alternatives in general, we already do so for `ld [hli/hld]` aka `ld [hl+/hl-]` aka `ldi/ldd [hl]`. But unlike `ldio`, none of those is an obvious candidate for deprecation. (Even `ldi/ldd` get *some* use; they were explicitly requested in #73.)

**Comment by Rangi42** [comment]
So far 11 votes to deprecate `ldio` vs just one to keep it; but 5 votes to keep `ld [$ff00+c]` vs 8 to deprecate.

**Review by ISSOtm — APPROVED** [review]
Yeah, `ldio` is uncontroversial enough, so let's act it out. We'll see about the other syntax in a separate thread.

**Comment by ISSOtm** [comment]
> Unpopular opinion... Too much deprecation. I say just remove it, and let the assembler errors notify people they need to update their code. It's a simple replace anyways.. I know lots of people who ignore those deprecation warnings until a release causes it to stop building... And then they might just stay on the old version anyways.

Oops, that was actually a good point, I think. Hmm, well, the main reason we're using deprecation warnings is to provide a nicer error message, so people who do upgrade are less confused and lost than getting a generic `syntax error`.

**Pull request merged**
