### PR TITLE
Implement smart linking

### LINKED ISSUE #82: Smart linking
20:51 <@beware> anjbe_: is "smart linking" something you can do? smart linking means: only include things that are actually referenced
    20:51 <@beware> this mostly helps with libraries
    20:51 <@beware> as not all of the library has to be linked
    20:51 <@beware> libraries tend to contain a lot of things a project doesn't need
    20:52 <@beware> i think a linker could do this transparently
    20:52 <@beware> (as in, as part of the linker)
    20:53 <@beware> to resolve "is symbol X being referenced", you need to trace it from the program's entry point
    20:53 <@beware> because a library can reference a symbol, but if that library is never used, then this reference doesn't mean it should be included
    20:54 <@beware> anything (that has a symbol) that is never referenced is "dead" (as in, dead code, dead data)

### PR DESCRIPTION
**Pull request by ISSOtm**
Fixes #82.

- [ ] Add a mechanism so that RGBASM-elided references are still emitted
- [ ] Add more tests covering more edge cases
- [ ] Sections should not be purged if fully constrained
- [ ] Apply smart linking *after* linker script (avoids errors & interacts with above)

### CODE REVIEW

**Comment by Rangi42** [comment]
I don't think `align` should constrain a section. Consider:

```
SECTION "ReverseBits", ROM0
ReverseBits::
	push hl
	ld h, HIGH(ReversedBitTable)
	ld l, a
	ld a, [hl]
	pop hl
	ret

SECTION "ReversedBitTable", ROM0, ALIGN[8]
ReversedBitTable::
x = 0
REPT 256
	; http://graphics.stanford.edu/~seander/bithacks.html#ReverseByteWith32Bits
	db LOW(((((x * $802) & $22110) | ((x * $8020) & $88440)) * $10101) >> 16)
x = x + 1
ENDR
```

If `ReverseBits` is never called, neither section is needed.

**Comment by ISSOtm** [comment]
That's not necessarily the case for sections with other constraints, either.

**Comment by Rangi42** [comment]
Is there an example of when some content would need to be in a specific bank or at a specific address, but could also be excluded entirely?

**Comment by Rangi42** [comment]
Superseded by #1382.

**Pull request closed without merging**
