### PR TITLE
Deprecate `LDH` with $00-$FF

### LINKED ISSUE #1570: Deprecate `ldh [$xx]`
`ldh [$ffxx]` is naturally valid, for use cases like `ldh [rLCDC]` where hardware.inc declares `DEF rLCDC EQU $FF40`, or `ldh [hVariable]` where `hVariable::` is in `HRAM` ($FF80-$FFFE).

However, RGBASM also quietly allows single-byte `ldh [$xx]`. So `ldh [$80]` would act just like `ldh [$ff80]`. This is arguably a footgun, since you might do `ldh [VBlank]` (the interrupt at $0040) and have it silently act like `ldh [rLCDC]`.

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #1570

### CODE REVIEW

**Review by ISSOtm — APPROVED** [review]
Colour me surprised if anyone *actually* relies on this!

**Comment by aparrish** [comment]
I don't know if this counts as "actually relying" on the deprecated behavior, but I'm writing a tool that generates both RGBDS code and machine code right now, and this deprecation means that I have to write a special case for this instruction specifically: when outputting RGBDS code, I have to write a 16-bit value in the code text, even though the underlying operand for the instructions `ldh [a8], a` and `ldh a, [a8]` are bytes. I understand the use case of people wanting to type `ldh [rLCDC], a`, but since the operand of the instruction has to be constant anyway, I wonder if it might be more intuitive for RGBDS to throw an error if the value of the operand in the code is specified as a 16-bit value *and* the value has anything other than `0xFF` in the upper byte, rather than deprecating the 8-bit form altogether.

(To be clear, programming the special case is not a big problem! I just came across this issue when I was trying to figure out why RGBDS does what it does in this case, and thought my input might be useful.)

**Comment by ISSOtm** [comment]
RGBDS already rejects values in the 0x100&ndash;0xEFFF range.

Couldn't you generate something like `ldh a, [$FF00 + %d]` and need no special codegen case?

**Comment by aparrish** [comment]
> Couldn't you generate something like ldh a, [$FF00 + %d] and need no special codegen case?

That's a good point, thank you—I'd already been taking advantage of RGBDS syntax for things like `HIGH()` and `LOW()`, and I suppose there isn't a canonical form for Game Boy opcode mnemonics anyway!

> Also there's no such thing as "a 16-bit value"; ldh [$42], a (which used to act like ldh [$ff42], a) is indistinguishable from ldh [$0042], a (which ought to be a "high byte is not $ff" error).

True, but there are other instructions with immediate operands that RGBDS ensures are 8-bit (or raises a truncation warning at least?), which is what I was thinking of. But I can see how it would be weird to make that distinction between `[` and `]`, which elsewhere is (almost) always two bytes. (If there were a mnemonic for these opcodes that allowed eight bit values only, strictly speaking I guess they would probably have to be `ldh a, n8` and `ldh n8, a` then, no brackets?) (not actually suggesting this)

The benefit of tipping programmers off that `ldh [rRAMG], a` is not going to do anything especially useful is definitely huge! A downside to this representation is that it's not immediately clear to the programmer that the underlying instruction only has one byte in its operand, not two, as is the case for all the other `ld` functions. But that downside isn't definitely isn't down enough to override the benefits of the current approach.

Anyway, thank you both for taking a moment to think/talk through this with me! Very helpful and generous of you to share your expertise.

**Pull request merged**
