### PR TITLE
Test the RGBASM state file output

### PR DESCRIPTION
**Pull request by Rangi42**

### CODE REVIEW

**Comment by ISSOtm** [comment]
With `-v`:

```diff
+Output filename C:/Users/RUNNER~1/AppData/Local/Temp/tmp.gZPcosTnUd
+Output filename C:/Users/RUNNER~1/AppData/Local/Temp/tmp.gZPcosTnUd
+State filename /tmp/tmp.gZPcosTnUd
+Assembling state-file/a.asm
+File "state-file/a.asm" is mmap()ped
```

???

**Comment by ISSOtm** [comment]
Oh, I guess I see why: `bash` is probably doing some path translation... but the `all:` prefix prevents that. I'll try a workaround.

**Comment by Rangi42** [comment]
> Oh, I guess I see why: `bash` is probably doing some path translation... but the `all:` prefix prevents that. I'll try a workaround.

Oh heck. XP  If necessary we could use a helper program like test/link/unmangle.cpp.

**Comment by ISSOtm** [comment]
That's what `cygpath` is for. I'm going to try using that.

**Review by ISSOtm — APPROVED** [review]

**Pull request merged**
