### PR TITLE
Allow DEF EQU, EQUS, or SET/= to define multiple variables

### LINKED ISSUE #801: [Feature request] Allow `DEF` to do simultaneous comma-separated assignments
For example, `DEF w = 1, x = 2, y = 3`. Or if it would avoid the string expansion issue from #803, then `DEF w, x, y = 1, 2, 3` (more like Python); possibly limit this to just `SET`/`=` definitions as well.

This ought to do all the definitions at once, not left to right or right to left. So you can swap two variables like `def p, q = q, p`.

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #801

This is a basic edit to the parser, with most of the edits being test cases and documentation.

### CODE REVIEW

**Comment by ISSOtm** [comment]
I'm unsure about this change for two reasons.

## Technical reason

I was fully expecting this change to introduce grammar errors. Consider what happens when the parser shifts in a `T_COMMA` after reading a definition. Is it a trailing comma, or is it preparing for a new definition, in which case expansions must be disabled in the lexer? It's impossible to know without seeing the next token...

According to [Bison's manual](https://www.gnu.org/software/bison/manual/html_node/Midrule-Conflicts.html#Midrule-Conflicts), the parser resolves the conflict by using a lookahead token, which should then cause the `T_ID` to be lexed before the midrule is executed. (That's how I understand the documentation, but it seems a bit unclear.)

## Rationale reason

Is this really useful? It's rare to see many assignments at once, and I think the examples provided in the tests don't look too readable.

**Comment by Rangi42** [comment]
Technically, I'd be surprised if this is the only parser rule that depends on Bison's single lookahead token.

On reflection you're right about its utility though. I think it would be more useful if it acted like Python and did all the assignments simultaneously; that would require building up a stack of symbol-value mappings as it parses, and then do all the assignments and free the stack at the end. That *would* be useful for the usual case of swapping two variables:

```
def _tmp = x
def x = y
def y = _tmp

def x = y, y = x
```

**Comment by ISSOtm** [comment]
It's not as much that a lookahead is necessary to decide (that's pretty standard), it's that the lookahead needs to be lexed **before** running the midrule that alters its lexing, in order to decide whether to run that midrule.

**Review by ISSOtm — CHANGES_REQUESTED** [review]
As I previously said, this doesn't work due to having to lex the following token before the midrule.
```asm
issotm@sheik-kitty ~/rgbds% cat /tmp/a.asm                                                                               [def-multiple|✔] 
def morphon equs "1", morphon equs "2"
def one equ morphon

	PRINTLN "{morphon}"
	PRINTLN "{one}"
issotm@sheik-kitty ~/rgbds% ./rgbasm /tmp/a.asm                                                                          [def-multiple|✔] 
ERROR: /tmp/a.asm(1):
    syntax error, unexpected number, expecting newline or identifier or end of buffer
while expanding symbol "morphon"
1
$1
error: Assembly aborted (1 error)!
```

This program will either fail due to lexing the token after the commas (`morphon`) before `lexer_ToggleStringExpansion(false)`, which is what happens here; or it may toggle expansions off and not enable them again (this is what the second line checks for).

**Comment by Rangi42** [comment]
You're right, I don't see a simple way around that failure. I'm closing this PR but leaving the feature request issue open: it might be simpler to parse with all the identifiers at once, like `def lo, hi = hi, lo` or `def fib1, fib2 = fib2, fib1 + fib2`.

**Pull request closed without merging**
