### PR TITLE
Implement `__INPUT_FILE__` and `__OUTPUT_FILE__`

### PR DESCRIPTION
**Pull request by Rangi42**
Based on discussion from #1120.

### CODE REVIEW

**Comment by ISSOtm** [comment]
From https://github.com/gbdev/rgbds/issues/1120#issuecomment-1374581584:

> I'd rather advocate for some kind of unique name passed by the build system, e.g. `-DUNIT_NAME=main`.

Closing for the same reason as the issue.

**Comment by Rangi42** [comment]
@ISSOtm Okay, there was some miscommunication; I asked in that issue "So would you be okay with a predefined `__OUTPUT_FILE__` string?" I don't know why you :+1:ed it.

**Comment by ISSOtm** [comment]
Ah! I meant to thumb-up the “or shall we close this?” part.

I understand now. Sorry!

**Comment by Rangi42** [comment]
I'd still like to make this available, since it doesn't have the uselessness problem of `__FILE__`, and in the event that someone needs this info, it's a bit tedious to do `-o foo.o -DUNIT_NAME=foo`.

**Comment by Rangi42** [comment]
> Ah! I meant to thumb-up the “or shall we close this?” part.
> 
> I understand now. Sorry!

Let's limit those to yes-no questions, meaning "yes". ;)

**Comment by ISSOtm** [comment]
I don't think it's tedious, it's trivial to add to a build system; and I don't want additional complexity if we can avoid it.

```mk
obj/%.o: src/%.c
    rgbasm ${ASFLAGS} $< -o $@ -DUNIT_NAME='$*' # or ${*F} if you want just the file name.
```

**Comment by Rangi42** [comment]
Sorry then, I may have overlooked the issue status.

**Pull request closed without merging**
